name: flutter_bitkub_app
packages:
  - "app/**"
  - "packages/**"

ignore:
  - "packages/features/auth/**"
  - "packages/features/home/**"
  - "packages/features/market/**"
  - "packages/features/setting/**"
  - "packages/features/trade/**"
  - "packages/features/wallet/**"

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze

  format:
    exec: flutter format . --set-exit-if-changed

  test:
    exec: flutter test

  clean:
    exec: flutter clean

  generate:flutter:
    exec: flutter pub run build_runner build --delete-conflicting-outputs